#!/usr/bin/env bash
# Copy the hosts file
cp /etc/hosts ~/hosts.new
# Change localhost resolution to 127.0.0.2
sed -i 's/^127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
# Add facebook.com resolution to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new
# Replace the old hosts file with the new one
sudo cp -f ~/hosts.new /etc/hosts
