#!/bin/bash
# Change localhost resolution to 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
# Change facebook.com resolution to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
